# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# Copy the everything server from the repository
COPY src/everything /app
# Copy the tsconfig file from the repo root required for the build
COPY tsconfig.json /tsconfig.json

WORKDIR /app

# Install dependencies and build the project using cache
RUN --mount=type=cache,target=/root/.npm npm install && npm run build

FROM node:22-alpine AS release

WORKDIR /app

# Copy built artifacts and package configuration
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

ENV NODE_ENV=production

# Install only production dependencies
RUN npm ci --ignore-scripts --omit=dev

EXPOSE 8080

CMD ["node", "dist/index.js"]
