# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy all files
COPY . .

# Install dependencies and build the 'everything' package
RUN cd src/everything && npm install --ignore-scripts && npm run build

# Expose a port if needed (default 8080)
EXPOSE 8080

# Start the MCP server from the 'everything' package
CMD ["node", "src/everything/dist/index.js"]
